### ISSUE TITLE
Need Work

### ISSUE THREAD

**Issue by sabrinabutton** [AYJACKSON-ICS4U/SAA-HackEd#5]
### Next thing to do?
I'm done the backend and now we just have to merge the functions into the front end- @AJ345 what can I help with to get the app done?

**Comment by AJ345** [comment]
can you make a simple html page and show how the back-end can be called?

**Comment by sabrinabutton** [comment]
yes, i will do that at lunch :)

**Comment by sabrinabutton** [comment]
I have a lot to do now to fix the backend, no longer need work!
